[package]
name = "crew"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = { version = "3.7.1", features = ["allocator_api"] }
env_logger = "0.9.0"
hashbrown = { version = "0.11.2", features = ["raw"] }
log = "0.4.14"
thiserror = "1.0.30"
